# Travis CI Configuration File

# Use Travis CI container-based infrastructure
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
# We only support PHP-supported versions of PHP.
# https://secure.php.net/supported-versions.php
# php:
#     - "5.6"
#     - "7.0"
#     - "7.1"
#     - "7.2"
#     - "7.3"

# WordPress version used in first build configuration.
# env:
#     - WP_VERSION=master
#     - WP_VERSION=5.0
#     - WP_VERSION=4.9
#     - WP_VERSION=4.8
#     - WP_VERSION=4.7
#     - WP_VERSION=4.6

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

# PHP/WP versions
matrix:
    include:
      # PHPunit 5
      - php: 5.6
        env: WP_VERSION=4.6
      - php: 5.6
        env: WP_VERSION=4.7
      - php: 5.6
        env: WP_VERSION=4.8
      - php: 5.6
        env: WP_VERSION=4.9
      # PHPUnit 6
      - php: 7.0
        env: WP_VERSION=4.8
      - php: 7.0
        env: WP_VERSION=4.9
      # PHPUnit 6
      - php: 7.1
        env: WP_VERSION=4.9
      - php: 7.1
        env: WP_VERSION=5.0
      # PHPUnit 7 support will come with https://core.trac.wordpress.org/ticket/43218
      # - php: 7.2
      #   env: WP_VERSION=4.9 WP_TESTS_DIR=/tmp/wordpress/tests/phpunit WP_CORE_DIR=/tmp/wordpress
      # - php: 7.2
      #   env: WP_VERSION=5.0 WP_TESTS_DIR=/tmp/wordpress/tests/phpunit WP_CORE_DIR=/tmp/wordpress
      # - php: 7.3
      #   env: WP_VERSION=4.9 WP_TESTS_DIR=/tmp/wordpress/tests/phpunit WP_CORE_DIR=/tmp/wordpress
      # - php: 7.3
      #   env: WP_VERSION=5.0 WP_TESTS_DIR=/tmp/wordpress/tests/phpunit WP_CORE_DIR=/tmp/wordpress

install:
  - composer install

# Clones WordPress and configures our testing environment.
before_script:
    - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit
    - export WP_CORE_DIR=/tmp/wordpress/
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
